### ISSUE TITLE
Act1 Mapa mental-Ana Kimberly Hernández Pérez 

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Anakimberly#1]
![IMG-20220919-WA0030](https://user-images.githubusercontent.com/112224202/191108293-1661218f-4e61-4ee5-b219-aaaaae408105.jpg)

**Comment by ErikCuevas03** [comment]
18.5 faltan elementos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
